<?php
require '../vendor/autoload.php';
require '../includes/db_connect.php';
session_start();

use Dompdf\Dompdf;
use Dompdf\Options;

// Security Check
if (!isset($_SESSION['logged_in']) || $_SESSION['role'] !== 'External_Admin') {
    exit("Unauthorized access.");
}

$scholarship_id = $_GET['scholarship_id'] ?? '';
$status         = $_GET['status'] ?? '';

// Build dynamic subtitle for the PDF header
$active_filters = [];
if (!empty($scholarship_id)) $active_filters[] = "Specific Scholarship";
if (!empty($status)) $active_filters[] = "Status: " . htmlspecialchars($status);

$subtitle = empty($active_filters) ? "All Scored Applications" : "Filters: " . implode(' | ', $active_filters);

$options = new Options();
$options->set('isHtml5ParserEnabled', true);
$dompdf = new Dompdf($options);

try {
    $query = "
        SELECT 
            a.ApplicationID,
            u.StudentID_Num, 
            u.FirstName, 
            u.LastName, 
            u.Major, 
            sch.Name AS ScholarshipName, 
            a.Status,
            a.TotalScore
        FROM application a
        JOIN users u ON a.UserID = u.UserID
        JOIN scholarship sch ON a.ScholarshipID = sch.ScholarshipID
        WHERE 1=1
    ";

    $params = [];

    if (!empty($scholarship_id)) {
        $query .= " AND a.ScholarshipID = :sid";
        $params['sid'] = $scholarship_id;
    }
    if (!empty($status)) {
        $query .= " AND a.Status = :status";
        $params['status'] = $status;
    }

    $query .= " ORDER BY sch.Name ASC, a.TotalScore DESC";

    $stmt = $pdo->prepare($query);
    $stmt->execute($params);
    $applications = $stmt->fetchAll();

} catch (PDOException $e) {
    die("Database Error: " . $e->getMessage());
}

$html = '
<style>
    body { font-family: "Helvetica", sans-serif; color: #333; }
    .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #000; padding-bottom: 10px; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th { background-color: #f8fafc; color: #64748b; font-size: 10px; text-transform: uppercase; padding: 10px; border: 1px solid #e2e8f0; text-align: left; }
    td { padding: 10px; border: 1px solid #e2e8f0; font-size: 10px; }
    .score-high { color: #16a34a; font-weight: bold; }
    .footer { margin-top: 30px; text-align: right; font-size: 9px; color: #94a3b8; }
</style>

<div class="header">
    <h1 style="margin:0;">ScholarLink Evaluation Report</h1>
    <p style="margin:5px 0; color:#2563eb; font-weight:bold;">External Evaluator Portal</p>
    <p style="font-size:12px; color:#333; font-weight:bold; margin-top:10px;">' . $subtitle . '</p>
    <p style="font-size:11px; color:#64748b;">Generated on: ' . date('F d, Y') . '</p>
</div>

<table>
    <thead>
        <tr>
            <th>App ID</th>
            <th>Applicant Name</th>
            <th>Program</th>
            <th>Scholarship</th>
            <th>Status</th>
            <th style="text-align:center;">Score</th>
        </tr>
    </thead>
    <tbody>';

if (empty($applications)) {
    $html .= '<tr><td colspan="6" style="text-align:center; padding: 20px;">No applications found matching these filters.</td></tr>';
} else {
    foreach ($applications as $app) {
        $score_display = $app['TotalScore'] > 0 ? '<span class="score-high">' . $app['TotalScore'] . ' / 100</span>' : '<span style="color:#94a3b8;">Pending</span>';
        
        $html .= '
            <tr>
                <td>APP-' . str_pad($app['ApplicationID'], 4, '0', STR_PAD_LEFT) . '</td>
                <td>' . htmlspecialchars($app['FirstName'] . ' ' . $app['LastName']) . '</td>
                <td>' . htmlspecialchars($app['Major']) . '</td>
                <td>' . htmlspecialchars($app['ScholarshipName']) . '</td>
                <td>' . htmlspecialchars($app['Status']) . '</td>
                <td style="text-align:center; font-size: 12px;">' . $score_display . '</td>
            </tr>';
    }
}

$html .= '
    </tbody>
</table>
<div class="footer">
    Generated by ScholarLink External Admin Portal &bull; ' . date('Y-m-d H:i:s') . '
</div>';

$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream("ScholarLink_Evaluation_Report_" . date('Y-m-d') . ".pdf", ["Attachment" => false]); 
exit();
?>